In [200]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [201]:
df_original=pd.read_csv("dataset/movie_metadata.csv")
df_original.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [202]:
df_original = df_original.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]
df_original

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,Avatar
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action|Adventure|Fantasy,Pirates of the Caribbean: At World's End
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action|Adventure|Thriller,Spectre
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action|Thriller,The Dark Knight Rises
4,Doug Walker,Doug Walker,Rob Walker,NaN,Documentary,Star Wars: Episode VII - The Force Awakens ...
...,...,...,...,...,...,...
5038,Scott Smith,Eric Mabius,Daphne Zuniga,Crystal Lowe,Comedy|Drama,Signed Sealed Delivered
5039,NaN,Natalie Zea,Valorie Curry,Sam Underwood,Crime|Drama|Mystery|Thriller,The Following
5040,Benjamin Roberds,Eva Boehnke,Maxwell Moody,David Chandler,Drama|Horror|Thriller,A Plague So Pleasant
5041,Daniel Hsia,Alan Ruck,Daniel Henney,Eliza Coupe,Comedy|Drama|Romance,Shanghai Calling
5042,Jon Gunn,John August,Brian Herzlinger,Jon Gunn,Documentary,My Date with Drew

In [203]:
df_original['actor_1_name'] = df_original['actor_1_name'].replace(np.nan, 'unknown') # replacing null values to "unknown"
df_original['actor_2_name'] = df_original['actor_2_name'].replace(np.nan, 'unknown')
df_original['actor_3_name'] = df_original['actor_3_name'].replace(np.nan, 'unknown')
df_original['director_name'] = df_original['director_name'].replace(np.nan, 'unknown')

In [204]:
df_original['genres'] = df_original['genres'].str.replace('|', ' ') # removing unnessesary bars

/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1402137748.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_original['genres'] = df_original['genres'].str.replace('|', ' ') # removing unnessesary bars

In [205]:
df_original['movie_title'] = df_original['movie_title'].str.lower() # lowering titile for the sake of simplicity

In [206]:
df_original['movie_title'] = df_original['movie_title'].apply(lambda x : x[:-1]) # removing unnessesary chars at the end of the titile

In [207]:
# preprocessing for credits.csv
credits = pd.read_csv('dataset/credits.csv')

In [208]:
from tmdbv3api import TMDb
import imdb
import json
import requests
from tmdbv3api import Movie
tmdb = TMDb()
tmdb.api_key = '87f1f400a3e1445d86fdd4366532e611'

In [219]:
# fetching genres using API
tmdb_movie = Movie()
def get_genre(x):    
        genres = []
        result = tmdb_movie.search(x)
        if result != []:
                movie_id = result[0].id
                response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
                data_json = response.json()
                if data_json['genres']:
                        genre_str = " " 
                        for i in range(len(data_json['genres'])):
                                genres.append(data_json['genres'][i]['name'])
                        return genre_str.join(genres)

In [220]:
movies_info = []

for i in range(5):
    link = "https://en.wikipedia.org/wiki/List_of_American_films_of_" + str(i+2018)
    df1 = pd.read_html(link, header=0)[2]
    df2 = pd.read_html(link, header=0)[3]
    df3 = pd.read_html(link, header=0)[4]
    df4 = pd.read_html(link, header=0)[5]
    df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

    movies_info.append(df)

/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1583965180.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1583965180.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1583965180.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1583965180.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1583965180.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [222]:
# adding the genre to the column for each dataset
for i in range(5):
    movies_info[i]['genres'] = movies_info[i]['Title'].map(lambda x: get_genre(str(x)))

In [223]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])
    
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [224]:
for i in range(5):
    movies_info[i] = movies_info[i][['Title','Cast and crew','genres']]
    movies_info[i] = movies_info[i].rename(columns={'Title':'movie_title'})
    movies_info[i]['director_name'] = movies_info[i]['Cast and crew'].map(lambda x: get_director(str(x)))
    movies_info[i]['actor_1_name'] = movies_info[i]['Cast and crew'].map(lambda x: get_actor1(str(x)))
    movies_info[i]['actor_2_name'] = movies_info[i]['Cast and crew'].map(lambda x: get_actor2(str(x)))
    movies_info[i]['actor_3_name'] = movies_info[i]['Cast and crew'].map(lambda x: get_actor3(str(x)))
    movies_info[i].loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]
    movies_info[i]['movie_title'] = movies_info[i]['movie_title'].str.lower()

In [232]:
new_df = pd.concat([movies_info[0], movies_info[1], movies_info[2], movies_info[3], movies_info[4]], ignore_index=True)
df_final = df_original.append(new_df,ignore_index=True)
df_final = df_final.drop("Cast and crew",axis=1)
df_final

/var/folders/g_/c68jffzd7552c4ffzwzthm1h0000gn/T/ipykernel_12007/1988796006.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df_original.append(new_df,ignore_index=True)

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...
...,...,...,...,...,...,...
6353,Kelly Fremon Craig,Rachel McAdams,Abby Ryder Fortson,Benny Safdie,Drama Comedy,"are you there god? it's me, margaret"
6354,Josh Gordon & Will Speck,Anthony Ramos,Naomi Scott,Zachary Quinto,Drama,distant
6355,Olivia Wilde,Florence Pugh,Harry Styles,Olivia Wilde,Drama Mystery Thriller,don't worry darling
6356,Nicholas Stoller,Billy Eichner,Luke Macfarlane,Jim Rash,Adventure Comedy Family Science Fiction,bros
6357,nan,nan,NaN,NaN,Comedy,NaN